[package]
name = "Market_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
BVC = { path = "../BVC" }
unitn_market_2022 = {version = "1.0.10", registry = "kellnr"} 